export let ListPedal = [
    {
        id: 1,
        title: "MOLEZINHA",
        creator: "Thais",
        km: 30,
        participants: [
            "Emanuelle",
            "Olivares",
            "Colares",
            "Séfora",
            "Layra",
            "Patrício",
            "Kenzo",
            "Élson",
            "Emília",
            "Naísa",
            "Neusa",
            "Anael",
            "Matias",
        ],
        rhythm: "Leve",
        largada: "Itaunas - Praça Central",
        dia: "04/08",
    },
    {
        id: 2,
        title: "BIKE EXTREME",
        creator: "Luiz Carlos",
        km: 10,
        participants: [
            "Emanuelle",
            "Olivares",
            "Colares",
            "Séfora",
            "Layra",
            "Patrício",
            "Kenzo",
            "Élson",
            "Emília",
            "Naísa",
            "Neusa",
            "Anael",
            "Matias",
        ],
        rhythm: "Intenso",
        largada: "Guriri - Posto Policial ",
        dia: "21/06",
    },
    {
        id: 3,
        title: "PEDAL RADICAL",
        creator: "Fernando",
        km: 5,
        participants: [
            "Emanuelle",
            "Olivares",
            "Colares",
            "Séfora",
            "Layra",
            "Patrício",
            "Kenzo",
            "Élson",
            "Emília",
            "Naísa",
            "Neusa",
            "Anael",
            "Matias",
        ],
        rhythm: "Leve",
        largada: "Guriri - Ponto Final",
        dia: "07/08",
    },
    {
        id: 4,
        title: "CROSS BIKE",
        creator: "Carlos",
        km: 300,
        participants: [
            "Emanuelle",
            "Olivares",
            "Colares",
            "Séfora",
            "Layra",
            "Patrício",
            "Kenzo",
            "Élson",
            "Emília",
            "Naísa",
            "Neusa",
            "Anael",
            "Matias",
        ],
        rhythm: "Extremo",
        largada: "São Mateus - Ibis Hotel",
        dia: "25/11",
    },
    {
        id: 5,
        title: "CABO CRIATIVIDADE",
        creator: "Pedro",
        km: 17,
        participants: [
            "Emanuelle",
            "Olivares",
            "Colares",
            "Séfora",
            "Layra",
            "Patrício",
            "Kenzo",
            "Élson",
            "Emília",
            "Naísa",
            "Neusa",
            "Anael",
            "Matias",
        ],
        rhythm: "Moderado",
        largada: "Guriri - Igrejinha",
        dia: "04/08",
    },
    {
        id: 6,
        title: "CABO CRIATIVIDADE",
        creator: "Pedro",
        km: 17,
        participants: [
            "Emanuelle",
            "Olivares",
            "Colares",
            "Séfora",
            "Layra",
            "Patrício",
            "Kenzo",
            "Élson",
            "Emília",
            "Naísa",
            "Neusa",
            "Anael",
            "Matias",
        ],
        rhythm: "Moderado",
        largada: "Guriri - Igrejinha",
        dia: "04/08",
    },
    {
        id: 7,
        title: "CABO CRIATIVIDADE",
        creator: "Pedro",
        km: 16,
        participants: [
            "Emanuelle",
            "Olivares",
            "Colares",
            "Séfora",
            "Layra",
            "Patrício",
            "Kenzo",
            "Élson",
            "Emília",
            "Naísa",
            "Neusa",
            "Anael",
            "Matias",
        ],
        rhythm: "Moderado",
        largada: "Guriri - Igrejinha",
        dia: "04/08",
    },
]